### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kenshinga** [liyuwei007036/smartCanteen#1]
no com.lc.core dependency?

**Comment by 2093949759** [comment]
dou you have com.lc.core now? if you have it. can you give me? thanks

**Comment by liyuwei007036** [comment]
> dou you have com.lc.core now? if you have it. can you give me? thanks
https://github.com/liyuwei007036/core

**Comment by liyuwei007036** [comment]
> dou你现在有com.lc.core吗？如果有的话。你能给我吗？谢谢



> 没有com.lc.core依赖性吗？

https://github.com/liyuwei007036/core

**Comment by liyuwei007036** [comment]
> no com.lc.core dependency?
https://github.com/liyuwei007036/core

**Comment by liyuwei007036** [comment]
> dou you have com.lc.core now? if you have it. can you give me? thanks

https://github.com/liyuwei007036/core
